
# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

PG_DATABASE_NAME = "bdr_database"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "centos65-x86_64-20140116"

  config.vm.define "master", primary: true do |server|
    server.vm.hostname = "master.pg"
    server.vm.network "private_network", ip: "192.168.3.2"

    server.vm.provision "shell", path: "scripts/master.sh", args: PG_DATABASE_NAME
  end

  config.vm.define "replica" do |server|
    server.vm.hostname = "replica.pg"
    server.vm.network "private_network", ip: "192.168.3.3"

    server.vm.provision "shell", path: "scripts/replica.sh", args: PG_DATABASE_NAME
  end

end
